# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2021 Moritz Hedtke <Moritz.Hedtke@t-online.de>

# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: projektwahl
      POSTGRES_PASSWORD: changeme
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # https://github.com/keycloak/keycloak-containers/blob/master/server/README.md
  keycloak:
    image: quay.io/keycloak/keycloak
    restart: always
    ports:
      - 8888:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin